### PR TITLE
build: relax version requirement of @typescript-eslint/utils

### LINKED ISSUE #42: relaxing dependency version of @typescript-eslint/utils
as of 2024-05-28, the version of 

[@typescript-eslint/utils](https://www.npmjs.com/package/@typescript-eslint/utils) is 7.11 already, installing `eslint-plugin-lingui` in the project with the latest eslint library creates nested dependencies because it require specifically `^5.61.0`

if the plugin does not depend on behavior specifically in version 5, can we relax the version to be `5 || 6 || 7`?

### PR DESCRIPTION
**Pull request by braineo**
close #42 

this seems to work for me

### CODE REVIEW

**Comment by braineo** [comment]
im on the oldest node LTS version. is node 16 a target version to support?

**Comment by thekip** [comment]
i think we can simply change Node.js version in the pipeline for 18.

**Comment by braineo** [comment]
> i think we can simply change Node.js version in the pipeline for 18.

oops, now it is a different issue

**Comment by timofei-iatsenko** [comment]
closing in favour https://github.com/lingui/eslint-plugin/pull/49

**Pull request closed without merging**
