### PR TITLE
ci: set up coverage, add the release and lint PR title workflows

### PR DESCRIPTION
**Pull request by andrii-bodnar**

### CODE REVIEW

**Comment by thekip** [comment]
I thought about implementing something from here https://github.com/semantic-release/semantic-release to fully automate github tags / releases creation together with changelist.

**Comment by andrii-bodnar** [comment]
It would be nice to have fully automated releases. For most projects I use the [release-it](https://www.npmjs.com/package/release-it) tool, this is also a good option

**Comment by thekip** [comment]
One more question, with release-it shouldn't we force all commit messages to be conventional commit? Or only PR titile which would be a source of merge commit name? 

Honestly, i prefer all commits to be a conventional commits. Looks like it's more popular solution then validating a PR title

**Review by thekip — APPROVED** [review]

**Comment by andrii-bodnar** [comment]
@thekip It won't force all commit messages to be conventional commits, but if to allow only squash merging + lint PR title - we will have only conventional commits in the main

**Pull request merged**
